### ISSUE TITLE
bad interpreter: /bin/env

### ISSUE THREAD

**Issue by mehdi-S** [96AA48/galaxygen#4]
```
-> % galaxygen
zsh: /usr/local/bin/galaxygen: bad interpreter: /bin/env: no such file or directory
```

tryed to use it on MacOS

**Comment by mehdi-S** [comment]
i now get this when gitcloning and ./galaxygen

```
-> # ./galaxygen
module.js:442
    throw err;
    ^

Error: Cannot find module 'cli'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/galaxygen/galaxygen:3:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by mehdi-S** [comment]
totally removing nodejs and installing it this way remove the issue :

```
sudo apt-get install python-software-properties python g++ make
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs
```
